# 本地开发（profile=dev）Nacos 注册中心配置
spring:
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: 124.221.104.56:8848
        namespace: 57f964ac-059c-4e2b-8138-47bba2b9afb0
        username: nacos
        password: nacos
        group: DEFAULT_GROUP
        register-enabled: true
        fail-fast: false
      config:
        server-addr: 124.221.104.56:8848
        namespace: 57f964ac-059c-4e2b-8138-47bba2b9afb0
        username: nacos
        password: nacos
        group: DEFAULT_GROUP
        enabled: false
