# 本地开发（profile=dev）公共配置
spring:
  devtools:
    restart:
      enabled: true
      poll-interval: 1s
      quiet-period: 400ms
      additional-exclude: static/**,public/**
    livereload:
      enabled: false
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: 124.221.104.56:8848
        namespace: 57f964ac-059c-4e2b-8138-47bba2b9afb0
        group: DEFAULT_GROUP
        register-enabled: true
        fail-fast: false
      config:
        enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      enabled: true
