server:
  port: 8085

spring:
  application:
    name: service-signal

clickhouse:
  enabled: true
  host: localhost
  port: 8123
  database: vrd_bigdata
  username: default
  password:
  connection-timeout: 10000
  socket-timeout: 30000
  query-timeout-seconds: 10
  max-page-size: 500
  insert-batch-size: 500
