# 本地开发（profile=dev）
spring:
  kafka:
    bootstrap-servers: 124.221.104.56:9092

mqtt:
  url: tcp://124.221.104.56:1883

clickhouse:
  host: 124.221.104.56
  port: 8123
  database: vrd_bigdata
  username: default
  password: ${CLICKHOUSE_PASSWORD:Wl12345}

storage:
  type: LOCAL
  local:
    base-path: D:/demo/Vehicle-Remote-Diagnosis/data/storage
    base-url: http://localhost:8080/storage

file:
  log:
    temp-path: D:/demo/Vehicle-Remote-Diagnosis/data/logs/temp
